- src/components/messages/MessageMetadataEditor.tsx
- src/i18n/en.ts
- src/i18n/it.ts
- src/pages/Compose.tsx
- src/pages/Message.tsx
- src/utils/operations.ts
This PR adds a checkbox to the MessageMetadataEditor component in order to allow to flag a payment as invalid after its due date.
> [#166761826] Add checkbox to disable a payment after its due date

- src/pages/SubscriptionService.tsx
This PR fixes the value type of the edited `max_allowed_payment_amount` property of the `Service` object in order to make it compliant with its interface definition.
> [#167151122] Fix max_allowed_payment_amount value on service edit

- package.json
- src/components/input/MetadataDescriptionEditor.css
- src/components/input/MetadataDescriptionEditor.tsx
- src/components/input/MetadataInput.tsx
- src/components/input/__tests__/metadata-keys.test.ts
- src/i18n/en.ts
- src/i18n/it.ts
- src/pages/SubscriptionService.tsx
This PR introduces:
- a new component to handle metadata description as markdown syntax;
- a mock for css in jest test;
> [#175205379] Add new MetadataDescriptionEditor component

- package.json
- yarn.lock
I had to close the original PR #137 and create this brand new one because the generated `yarn.lock` was somehow corrupted and the project didn't build.
I quote the original:
>Remove snyk dependency, used in prepublish npm script.
Some second or third level dependencies have been locked (through resolutions) to a specific version that could still run on a ^8.0.0 node engine.
Please @pp-ps review this and confirm changes are good.
> remove snyk script and upgrade yarn lock

- src/components/input/MarkdownEditor.css
- src/components/input/MarkdownEditor.tsx
- src/components/input/MetadataDescriptionEditor.css
- src/components/input/MetadataInput.tsx
> [#175915737] Add markdown editor for cta metadata field

- package.json
- yarn.lock
`reactstrap` was introduced in https://github.com/pagopa/io-developer-portal-frontend/pull/151 but the update `yarn.lock` wasn't committed.
> [#175915737] Fix missing packages

- .devops/deploy-pipelines.yml
This PR disables the _git checkout_ for the deploy stage, in order to avoid copying the code to the storage.
> [#176069616] Disable checkout in deploy stage

- .devops/deploy-pipelines.yml
This PR correctly renames the variables used in ci/cd step _purge cdn_:
- RESOURCE_GROUP_AZURE  --> PRODUCTION_RESOURCE_GROUP_NAME;
- ENDPOINT_AZURE --> PRODUCTION_CDN_ENDPOINT;
- PROFILE_NAME_CDN_AZURE --> PRODUCTION_CDN_PROFILE_NAME.
> [#176014693] Rename pipeline vars - purge cdn

- src/components/input/MetadataInput.tsx
- src/pages/SubscriptionService.tsx
- User can edit authorized IP (`authorized_cidrs`) and Service Logo and service metadata without:
- `token_name`
- `is_visible`
- `max_payment_allowed`
- `authorized_recipients`
- `scope` for visible services
A limited user should update `service_metadata` and `authorized_cidrs` to reduce the workload for Admins to fix wrong or missing information.
- no test
> [#ENTE-36] User can edit service metadata fields

- src/components/input/MetadataInput.tsx
With this PR I'll fix a missing field `web_url` inside the service metadata form.
> [#Ente-72] Fix for a missing web_url form field

- src/pages/SubscriptionService.tsx
Actually, as Admin, you can send a review request to the backend, but you got a 403 silently. With this fix, the button "Publish" now is disabled for Admin user.
> [#Ente-123] As admin I can't publish a review request on JIRA

- src/components/Header.tsx
- src/pages/Login.tsx
- src/utils/session/index.ts
- src/utils/session/msal.ts
This is a refactor that re-arrange session handling, to make it generic and allow for methods other Azure Active Directory to be implemented. No changes in the behavior are meant for this PR.
It pairs what's been done in https://github.com/pagopa/io-developer-portal-backend/pull/144
> [#IC-116] Abstract session handling

- src/components/input/AdminFields.tsx
- src/pages/SubscriptionService.tsx
The value `custom_flow_name` for `SpecialServices` cannot be set or edit.
The wrong handler was used on input `onBlur` event.
The types are fixed accordingly with the implementation.
**Cheklist:**
> [#IC-234] Fix value change on custom_flow_name metadata

- src/components/modal/DisableService.tsx
- src/components/modal/Modal.css
- src/components/modal/NewService.tsx
- src/components/modal/PublishService.tsx
- src/components/subscription-migrations/MigrationsPanel.tsx
- src/components/subscription-migrations/SummaryBox.tsx
- src/i18n/en.ts
- src/i18n/it.ts
- src/pages/Dashboard.tsx
- src/utils/feature-flags.ts
This PR scaffolds UI components that will control subscriptions migration process. The UI is protected by a feature flag as the feature is yet to be completed.
**How it works**
Introduced components will show if:
* application instance is of type `selfcare`
* feature flag `FF_SUBSCRIPTION_MIGRATIONS_ENABLED` is set to `true`
So far, migration data isn't fetched from API, hence the UI will show a static "empty" placeholder
**Change details**
See commit list
**Screenshots**
> [#IC-322] Scaffolding subscription migrations UI

- package.json
- src/utils/__tests__/createMessagecontent.test.ts
- src/utils/__tests__/paymentdata.test.ts
Add `--no-strict` to generate types in `package.json` to be able to create a valid content message due to prevent a bug with `io-ts` version 1.
> Add no-strict to generate types and some tests

- src/components/subscriptions/SubscriptionsLoader.css
- src/components/subscriptions/SubscriptionsLoader.tsx
- src/i18n/en.ts
- src/i18n/it.ts
- src/pages/Profile.css
- src/pages/Profile.tsx
**Added pagination capability to user's subscription list**
Now the first 20 services will be loaded, and if the user has more services, there will be the possibility to load the remainins by clicking on the appropriate button at the bottom of the list.
- Update *Profile* page with subscriptions pagination capability
- Add *stylesheet file* to *Profile* page
- Add *progress bar* when subscriptions are loading
Before the changes, all services were loaded all at once and this could create loading problems for users with many services (cases with thousands of services).
**Integration Tests with developer-portal-backend**
* (Tested with 16 user’s subscriptions available account)*
* limit=20
* offset=0 limit=20 —> OK Load One Shot, button “Carica altri servizi” is hidden
*   limit=8
* …
> [#IOPAE-104] Subscriptions pagination

- openapi.html
This PR will update the OpenAPI reference link from https://raw.githubusercontent.com/teamdigitale/io-functions-services/master/openapi/index.yaml to https://raw.githubusercontent.com/pagopa/io-functions-services/master/openapi/index.yaml
> [#IOPAE-76] Update openapi reference link

- package.json
This PR add the missing folder `assets` to the build process.
> [#IOPAE-136] Add assets folder to postbuild command

- src/components/subscriptions/ApiKey.css
- src/components/subscriptions/ApiKey.tsx
- src/components/subscriptions/InfoIconWithTooltip.css
- src/components/subscriptions/InfoIconWithTooltip.tsx
- src/components/subscriptions/TitleWithTooltip.tsx
- src/i18n/en.ts
- src/i18n/it.ts
- src/pages/SubscriptionService.tsx
Added the possibility to manage `require_secure_channels` checkbox _(labeled as Sensitive Service)_ in service edit/detail section.
This new feature has been developed in the context of _"privacy critical"_ services and the need to control the `require_secure_channels` flag via the Developer Portal.
- refactor of InfoIconWithTootlip generic component (now used both in Manage Key Info and Sensitive Service Info)
- added `require_secure_channels` checkbox in service detail/update section
Tested in local with backend and `prod` environment.
https://github.com/pagopa/io-developer-portal-frontend/assets/118166285/7288ccb1-a00a-449e-8afe-b8f3fb55c786
depends on https://github.com/pagopa/io-developer-portal-backend/pull/212
> [#IOPAE-586] Add require_secure_channels checkbox to service update

- src/i18n/en.ts
- src/i18n/it.ts
- src/pages/SubscriptionService.tsx
We introduce a https://github.com/pagopa/io-developer-portal-backend/pull/215 check on [io-developer-portal-backend](https://github.com/pagopa/io-developer-portal-backend)  to block update service request if there are changes "in progress" by Services CMS "parallel" system.
Therefore, in the case of a service update that returns a `409` with detail=`sync_check_error`, a specific error is shown informing the user of what happened.
_Watch video below to better appreciate development._
- add logic to display error on `src/pages/SubscriptionService.tsx`
- add error message translations
Local `dev` mode with mocked backend responses.
https://github.com/pagopa/io-developer-portal-frontend/assets/118166285/ad685b70-3f96-4232-842a-829c032b2e4d
> [IOPAE-908] Sync check error display
