pagopa/io-developer-portal-frontend

- index.html
This PR adds the Content Security Policy meta tags for the workers in order to allow their creation.
> [#167151068] Set Content Security Policy meta tags for workers

- azure-pipelines.yml
- azure-templates/deploy-steps.yml
- azure-templates/make-build-steps.yml
**Implementation notes**:
- the Azure DevOps task _ AzureFileCopy_ has been used to upload the files generated by the build (in the `/dist` directory) to the given container blob in the specified storage account (specified in the pipeline variables) 
- to successfully execute the above command during the pipeline execution it is required to add role "Storage Blob Data Contributor" to the service principal generated when creating the Azure Resource Manager service connection in Azure DevOps
- the above role assignment can be performed in the Azure portal, going in the Subscription page under the Access Control (IAM) section (the IO CI/CD documentation will be updated with all steps required)
- the `make_build ` job (i.e. the template `make-build-steps.yml`) assumes that 5 environment …
> [#171746077] Added azure pipeline

- src/pages/LogoOrganizations.tsx
- src/pages/SubscriptionService.tsx
This PR fix `logoPath` parameter for `UploadLogo` component
> [#175441170] Fix logoPath for UploadLogo component

- src/pages/LogoOrganizations.tsx
- src/pages/SubscriptionService.tsx
This PR convert _serviceId_ to lowercase in logo path.
For example, given a _serviceId_ TEST123:
- testcdn.it/logos/services/test123.png
> [#175441170] Convert serviceId to lowercase in logo path

- src/pages/LogoOrganizations.tsx
- src/pages/SubscriptionService.tsx
This PR fix logo path of a service or organization, converting lowercase only _serviceId/organizationsId_
> [#175441170] Fix service/organization logo path

- .devops/deploy-pipelines.yml
This PR fix bundle path in deploy stage
> [#176069616] Fix path in deploy stage

- src/components/input/MetadataInput.tsx
- src/utils/validators.ts
With this PR we have fixed the CTA Validation after merge #165 to master
> [#Ente-72] Fix CTA Validation

- src/utils/validators.ts
Fix on validation on `token name` field after merged #165
> [#Ente-72] Fix validation on token name

- src/pages/SubscriptionService.tsx
- src/utils/validators.ts
Fix a missed validation on field max_allowed_payment_amount field
> [#Ente-72] Fix a missed validation on max_allowed_payment_amount field

- src/utils/session/index.ts
- src/utils/session/selfcare.ts
Handle JWT session using SelfCare SSO
https://github.com/pagopa/io-developer-portal-backend/pull/146 is required
> [#IC-117] SelfCare session handling

- src/utils/session/selfcare.ts
Store a session token coming downstream of a login session.
The token is red from the url's hash and stored in the session storage. The session validation is then performed as usual
> [#IC-153] Store incoming SessionToken

- src/components/subscription-migrations/MigrationsPanel.tsx
- src/i18n/en.ts
- src/i18n/it.ts
Allow SelfCare user to start the procedure to claim ownership of their subscriptions actually owned by a Delegate
> [#IC-323] Claim subscription ownership 

- index.tsx
- src/components/Aside.tsx
- src/components/Header.tsx
- src/components/messages/MessageMetadataEditor.tsx
- src/components/templates/TemplatesEditor.tsx
- src/i18n/it.ts
> Fix linter

- index.tsx
- src/components/Aside.tsx
- src/components/Footer.tsx
- src/components/Header.tsx
- src/components/input/MarkdownEditor.css
- src/components/input/MarkdownEditor.tsx
- src/components/messages/MessageMetadataEditor.tsx
- src/components/templates/TemplatesEditor.css
- src/components/templates/TemplatesEditor.tsx
- src/i18n/it.ts
- src/pages/Compose.tsx
- src/pages/Templates.tsx
Fixed overflow on markdown editor
> Fix overflow on markdown editor

- .devops/azure-templates/make-build-selfcare.yml
> [#IOPSC-85] Set portal head title to `App IO`

- src/pages/Profile.tsx
> [#IOPSC-87] - Use Organization name as page title

- src/components/subscription-migrations/DelegateItem.tsx
- src/components/subscription-migrations/LatestMigrationsPanel.tsx
- src/components/subscription-migrations/MigrationsPanel.tsx
- src/components/subscription-migrations/SelectorInput.tsx
- src/components/subscription-migrations/SummaryBox.tsx
- src/pages/Dashboard.tsx
See commit list
To list a resume of previously started migrations, with their completion status, in order to help user get the situation at a glance
> [#IOPAE-23] implement UI for latest migrations

- src/components/Header.tsx
> [#IOPSC-104] Show organization name

- src/components/modal/NewService.tsx
- src/pages/Profile.tsx
- src/pages/SubscriptionService.tsx
> [#IOPAE-28] Disable editing of `organization_fiscal_code` and `organization_name` for `SelfCare` users

- src/components/subscription-migrations/DelegateItem.tsx
- src/components/subscription-migrations/MigrationsPanel.tsx
- src/components/subscription-migrations/SummaryBox.tsx
- src/i18n/en.ts
- src/i18n/it.ts
> [#IOPAE-19] Review texts

- src/pages/Profile.tsx
**Fix Admin services pagination**
- Add missing user email param to *SubscriptionLoader* component *onClick* event
Bug fix related to Operations issue
Tested in localhost
> [#IOPSC-129] fix admin services pagination

- src/components/subscriptions/ApiKey.css
- src/components/subscriptions/ApiKey.tsx
- src/components/subscriptions/CopyToClipboard.tsx
- src/components/subscriptions/KeyMasker.tsx
- src/components/subscriptions/ServiceCard.tsx
- src/components/subscriptions/ToggleServiceInfo.tsx
- src/i18n/en.ts
- src/i18n/it.ts
- src/pages/Profile.tsx
Added new Manage Key info box in _Services_ section.
- New Manage Key box in Services section
- Same keys layout in service card component
- Added "copy to clipboard" key feature
- 
Frontend part of the Service **Manage Flow**.
> [#IOPAE-125] Add Services Manage Flow

- package.json
This PR add `privacypolicy.html` and `tos.html` to the dist folder on build execution.
> [#IOPAE-135] Add privacypolicy and tos html pages to dist

- package.json
- privacypolicy.html
- tos.html
This PR remove the reference to the OneTrust for JS script and add the reference to the local one.
> [#IOPAE-136]  Fix privacy policy tos assets fold

- src/components/subscription-migrations/DelegateItem.tsx
- src/components/subscription-migrations/LatestMigrationsPanel.tsx
- src/components/subscription-migrations/SummaryBox.tsx
- src/i18n/en.ts
- src/i18n/it.ts
Add lastUpdate date on services import status.
- Add lastUpdate info on import status list
In order to have more knowledge of when an import operation was performed.
> [#IOPAE-63] Add lastUpdate date on imports

- src/i18n/en.ts
- src/i18n/it.ts
- update text about in place guide for services import
- feedback about a better explain on actions
> Iopae 227 update import services inplace guide

- src/pages/Dashboard.tsx
We add a static and temporary disclaimer to inform users of disservices due to an extraordinary maintenance intervention on July 31st from 8 to 24.
_This message will be updated on July 31st (with a different copy) an then removed._
- Added static `Alert` on _**Dashboard**_
> [#IOPAE-453] Add temporary disclaimer for APIM v2 migration

- scheduled-info.json
- src/i18n/en.ts
- src/i18n/it.ts
Update scheduled disclaimers for Apim V2 migration of 7th August.
- `./scheduled-info.json` with 2 new scheduled disclaimers
We need to inform IO BackOffice users that a major update of the API management system will take place between 08:00 and 24:00 on Monday 7 August. During this period, service management APIs and services on the Developer Portal and the Reserved Area will be temporarily unavailable.
> [#IOPAE-481] New apim v2 migration scheduled disclaimers

- src/i18n/en.ts
- src/i18n/it.ts
- src/pages/SubscriptionService.tsx
Add delete_check_error when trying to update a service that had been deleted
> [#IOPAE-1011]add error for trying to update deleted service

- src/i18n/en.ts
- src/i18n/it.ts
- src/pages/SubscriptionService.tsx
Avoid having multiple service with the same name for an organization by checking for.
> [#IOPAE-1089] Check if the service is a pure duplicate on service activation

- src/i18n/it.ts
> [IOPAE-1089] fix typo
